name: Docker Compose Test

on:
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and run Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d
        docker-compose -f docker-compose.yml ps  # Display running containers for verification
        # You can add more commands here for testing your services

    - name: Wait for Services to Start
      run: sleep 15s

    - name: Test Backend with curl
      run: curl -I http://localhost:5000/message

    - name: Test Frontend with curl
      run: curl -I http://localhost:8080

    - name: Stop Docker Compose
      run: docker-compose -f docker-compose.yml down
